storage: /verdaccio/storage
plugins: /verdaccio/plugins

auth:
  ldap:
    type: ldap
    client_options:
      url: ldap://lldap:3890
      searchBase: ou=people,dc=havokhound,dc=co,dc=uk
      searchFilter: "(uid={{username}})"
      adminDn: uid=admin,ou=people,dc=havokhound,dc=co,dc=uk
      adminPassword: "${VERDACCIO_LDAP_BIND_PASSWORD}"

uplinks: {}

packages:
  "@*/*":
    access: $anonymous
    publish: $authenticated
    unpublish: $authenticated

  "**":
    access: $anonymous
    publish: $authenticated
    unpublish: $authenticated

server:
  keepAliveTimeout: 60

web:
  title: Havokhound NPM Registry

log:
  type: stdout
  format: pretty
  level: http

url_prefix: "/"
